name: ecommerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.1.3
  shimmer: ^2.0.0
  lottie: ^2.2.0
  connectivity_plus: ^3.0.3

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/lotties/